//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mlTest.db.con
{
    using System;
    using System.Collections.Generic;
    
    public partial class ML
    {
        public int IDX { get; set; }
        public string TITLE { get; set; }
        public string CONTENT { get; set; }
        public Nullable<System.DateTime> REG_DT { get; set; }
        public Nullable<System.DateTime> EDT_DT { get; set; }
        public string REG_NM { get; set; }
        public string EDT_NM { get; set; }
    }
}
